language: c++

compiler:
  - gcc

install:
 - sudo apt-get update
 - sudo apt-get install libopencv-dev libboost-all-dev libcurl3

script:
  - git submodule update --init --recursive  
  - make build
